<a href="https://colab.research.google.com/github/KSingh28/Tensorflow_projects/blob/main/1_Tensorflow_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import tensorflow as tf
import numpy as np

In [3]:
tensor_zero_dim=tf.constant(8)
print(tensor_zero_dim)

tf.Tensor(8, shape=(), dtype=int32)


In [6]:
tensor_one_dim_s1=tf.constant([1,9,7])
print(tensor_one_dim_s1)
tensor_one_dim_s2=tf.constant([1,9,7,-4,5.])
print(tensor_one_dim_s2)

tf.Tensor([1 9 7], shape=(3,), dtype=int32)
tf.Tensor([ 1.  9.  7. -4.  5.], shape=(5,), dtype=float32)


Create 2D Tensor

In [7]:
tensor_two_dim=tf.constant([
    [1,6,7],
    [2,5,7],
    [8,9,5],
    [2,4,3]
    ])
print(tensor_two_dim)

tf.Tensor(
[[1 6 7]
 [2 5 7]
 [8 9 5]
 [2 4 3]], shape=(4, 3), dtype=int32)


**Create 3D Tensor**

In [9]:
tensor_three_dim=tf.constant([
    [[1,6,7],
    [2,5,7]],

    [[8,9,5],
    [2,4,3]],

    [[9,9,8],
    [5,4,5]],

    [[3,6,1],
    [7,3,2]],
    ])
print(tensor_three_dim)


tf.Tensor(
[[[1 6 7]
  [2 5 7]]

 [[8 9 5]
  [2 4 3]]

 [[9 9 8]
  [5 4 5]]

 [[3 6 1]
  [7 3 2]]], shape=(4, 2, 3), dtype=int32)
(4, 2, 3)


**Different print functions to use**

In [10]:
print(tensor_three_dim.shape)
print(tensor_three_dim.ndim)

(4, 2, 3)
3


**Create 4D Tensor**

In [11]:
tensor_four_dim=tf.constant([
   [ [[1,6,7],
    [2,5,7]],

    [[8,9,5],
    [2,4,3]],

    [[9,9,8],
    [5,4,5]],

    [[3,6,1],
    [7,3,2]],
   ],

   [ [[3,7,7],
    [1,1,7]],

    [[8,9,3],
    [2,7,6]],

    [[9,7,8],
    [2,4,5]],

    [[5,7,1],
    [2,5,9]],
   ],


   [ [[1,8,3],
    [4,6,9]],

    [[5,6,5],
    [3,5,8]],

    [[7,4,7],
    [2,4,3]],

    [[4,1,1],
    [8,9,3]],

   ]
    ])
print(tensor_four_dim)

tf.Tensor(
[[[[1 6 7]
   [2 5 7]]

  [[8 9 5]
   [2 4 3]]

  [[9 9 8]
   [5 4 5]]

  [[3 6 1]
   [7 3 2]]]


 [[[3 7 7]
   [1 1 7]]

  [[8 9 3]
   [2 7 6]]

  [[9 7 8]
   [2 4 5]]

  [[5 7 1]
   [2 5 9]]]


 [[[1 8 3]
   [4 6 9]]

  [[5 6 5]
   [3 5 8]]

  [[7 4 7]
   [2 4 3]]

  [[4 1 1]
   [8 9 3]]]], shape=(3, 4, 2, 3), dtype=int32)


**Data Conversion**
1.Convert to float
2.Convert to float16-to save memory
3.Cast float to int
4.Cast to bool
5. String Tensor


In [23]:
tensor_one_dim_c1=tf.constant([1,9,7,-4,5],dtype=tf.float32)
print(tensor_one_dim_c1)
tensor_one_dim_c2=tf.constant([1.,9,7,-4,5],dtype=tf.float16)
print(tensor_one_dim_c2)
tensor_one_dim_casted=tf.cast(tensor_one_dim_c2,dtype=tf.int16)
print(tensor_one_dim_casted)
tensor_one_dim_boo=tf.cast(tensor_one_dim_c2,dtype=tf.bool)
print(tensor_one_dim_boo)
tensor_string=tf.constant(['hello world','hola'])
print(tensor_string)

tf.Tensor([ 1.  9.  7. -4.  5.], shape=(5,), dtype=float32)
tf.Tensor([ 1.  9.  7. -4.  5.], shape=(5,), dtype=float16)
tf.Tensor([ 1  9  7 -4  5], shape=(5,), dtype=int16)
tf.Tensor([ True  True  True  True  True], shape=(5,), dtype=bool)
tf.Tensor([b'hello world' b'hola'], shape=(2,), dtype=string)


**Convert numpy array into tensor**

In [26]:
np_array=np.array([1,2,4])
print(np_array)
np_array_converted=tf.convert_to_tensor(np_array)
print(np_array_converted)

[1 2 4]
tf.Tensor([1 2 4], shape=(3,), dtype=int64)


**Tensorflow eye method(tf.eye)- Construct an identity matrix**

In [35]:
test_eye_tensor = tf.eye(
    num_rows=4,
    num_columns=None,
    batch_shape=None,
    dtype=tf.dtypes.float32,
    name=None
)
print(test_eye_tensor)

three_eye_tensor = tf.eye(
    num_rows=4,
    num_columns=None,
    batch_shape=None,
    dtype=tf.dtypes.float16,
    name=None
)
print(3*three_eye_tensor)

boo_eye_tensor = tf.eye(
    num_rows=4,
    num_columns=None,
    batch_shape=None,
    dtype=tf.dtypes.bool,
    name=None
)
print(3*three_eye_tensor)

fivebyfive_eye_tensor = tf.eye(
    num_rows=5,
    num_columns=3,
    batch_shape=None,
    dtype=tf.dtypes.float32,
    name=None
)
print(fivebyfive_eye_tensor)

tf.Tensor(
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]], shape=(4, 4), dtype=float32)
tf.Tensor(
[[3. 0. 0. 0.]
 [0. 3. 0. 0.]
 [0. 0. 3. 0.]
 [0. 0. 0. 3.]], shape=(4, 4), dtype=float16)
tf.Tensor(
[[3. 0. 0. 0.]
 [0. 3. 0. 0.]
 [0. 0. 3. 0.]
 [0. 0. 0. 3.]], shape=(4, 4), dtype=float16)
tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(5, 3), dtype=float32)


In [37]:
batch_eye_tensor = tf.eye(
    num_rows=5,
    num_columns=None,
    batch_shape=[2,],
    dtype=tf.dtypes.float32,
    name=None
)
print(batch_eye_tensor)

tf.Tensor(
[[[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]

 [[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]], shape=(2, 5, 5), dtype=float32)


#Fill method

In [39]:
fill_tensor=tf.fill(
    [1,3,4],5,None
)
print(fill_tensor)

tf.Tensor(
[[[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]], shape=(1, 3, 4), dtype=int32)


#Ones method
1.Zero tensor(tf.zeroes)
2.Ones tensor
3.ones_like- Create tensor of all ones that has the same shape as input

In [42]:
ones_tensor=tf.ones(
    [1,5],
    dtype=tf.dtypes.float16,
    name=None
    )
print(ones_tensor)

ones_like_tensor = tf.ones_like(fill_tensor)
print(ones_like_tensor)

tf.Tensor([[1. 1. 1. 1. 1.]], shape=(1, 5), dtype=float16)
tf.Tensor(
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]], shape=(1, 3, 4), dtype=int32)


**tf.shape method**
Contaianing the shape of the input tensor
**tf.rank method**

In [47]:
print(tf.shape(ones_tensor))
t=tf.constant([[1,5,5],[25,6,5]])
tf.rank(t)


tf.Tensor([1 5], shape=(2,), dtype=int32)


<tf.Tensor: shape=(), dtype=int32, numpy=2>

tf.size method- returns size of tensor

In [49]:
t=tf.constant([[1,5,5],[25,6,5],[5,4,9]])
tf.size(t)
tf.size(t,out_type=tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=9.0>

#**Random Tensor**

In [52]:
ran_tensor = tf.random.normal(
    [4,2],
    mean=0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(ran_tensor)

ran_tensor = tf.random.normal(
    [4,2],
    mean=80,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(ran_tensor)

tf.Tensor(
[[-0.8260501   0.3456349 ]
 [ 1.9474539  -0.07468411]
 [ 2.5874043   1.3668696 ]
 [-0.19406663  0.9581556 ]], shape=(4, 2), dtype=float32)
tf.Tensor(
[[80.830666 78.22471 ]
 [80.17331  79.598694]
 [80.99979  80.561935]
 [80.043755 80.10987 ]], shape=(4, 2), dtype=float32)


#Uniform distribution- max value defaults to 1,min to 0 in tensorflow
Need to define maxval when datatype=integer

In [60]:
uniform_tensor=tf.random.uniform(
    (2,), minval=0,
    maxval=None,
    dtype=tf.dtypes.float32,
    seed=None, name=None
)
print(uniform_tensor)

uniform_tensor_two=tf.random.uniform(
    (2,), minval=0,
    maxval=9,
    dtype=tf.dtypes.float32,
    seed=None, name=None
)
print(uniform_tensor_two)

uniform_tensor_three=tf.random.uniform(
    (2,), minval=0,
    maxval=9,
    dtype=tf.dtypes.int32,
    seed=None, name=None
)
print(uniform_tensor_three)

tf.Tensor([0.65782845 0.58047044], shape=(2,), dtype=float32)
tf.Tensor([6.568997   0.08376324], shape=(2,), dtype=float32)
tf.Tensor([1 7], shape=(2,), dtype=int32)


**tf.random.set_seed**
To create a reproducible sequence of tensors across multiple calls

In [64]:
tf.random.set_seed(4)
print(tf.random.uniform(shape=[3,], maxval=8, dtype=tf.int32, seed=9))
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([2 4 1], shape=(3,), dtype=int32)
tf.Tensor([3 4 3], shape=(3,), dtype=int32)
tf.Tensor([3 4 0], shape=(3,), dtype=int32)


**Indexing**

In [12]:
tensor_indexing=tf.constant([3,4,8,9,12,5,88])
print(tensor_indexing)
print(tensor_indexing[0:3])
print(tensor_indexing[1:5])
#print from 4,8,9,12,5
print(tensor_indexing[1:5])
print(tensor_indexing[1:5+1])
#include the steps
print(tensor_indexing[1:6:2])
#when don't specify minindex, its considered as 0
print(tensor_indexing[:4])
#when no maxindex, considered end of index
print(tensor_indexing[1:])
print(tensor_indexing[1:-1])

tf.Tensor([ 3  4  8  9 12  5 88], shape=(7,), dtype=int32)
tf.Tensor([3 4 8], shape=(3,), dtype=int32)
tf.Tensor([ 4  8  9 12], shape=(4,), dtype=int32)
tf.Tensor([ 4  8  9 12], shape=(4,), dtype=int32)
tf.Tensor([ 4  8  9 12  5], shape=(5,), dtype=int32)
tf.Tensor([4 9 5], shape=(3,), dtype=int32)
tf.Tensor([3 4 8 9], shape=(4,), dtype=int32)
tf.Tensor([ 4  8  9 12  5 88], shape=(6,), dtype=int32)
tf.Tensor([ 4  8  9 12  5], shape=(5,), dtype=int32)


#Indexing in 2D tensors

In [18]:
tensor_two_dim=tf.constant([
    [1,6,7],
    [2,5,7],
    [8,9,5],
    [2,4,3]
    ])
#first oart is rows and second part is column
print(tensor_two_dim[0:3,0:2])
#first 3 rows and all columns
print(tensor_two_dim[0:3,:])
#particular row and all columns
print(tensor_two_dim[2,:])
#particular row(3) and 2 column
print(tensor_two_dim[2,1])
#all the rows in 2 ways(three dots picks up all the indexes)
print(tensor_two_dim[:,1])
print(tensor_two_dim[...,1])

tf.Tensor(
[[1 6]
 [2 5]
 [8 9]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[1 6 7]
 [2 5 7]
 [8 9 5]], shape=(3, 3), dtype=int32)
tf.Tensor([8 9 5], shape=(3,), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)
tf.Tensor([6 5 9 4], shape=(4,), dtype=int32)
tf.Tensor([6 5 9 4], shape=(4,), dtype=int32)


#Indexing in 3D tensors

In [23]:
tensor_three_dim=tf.constant([
    [[1,6,7],
    [2,5,7]],

    [[8,9,5],
    [2,4,3]],

    [[9,9,8],
    [5,4,5]],

    [[3,6,1],
    [7,3,2]],
    ])
#pick first index
print(tensor_three_dim[0,:,:])
#pick first index first row
print(tensor_three_dim[0,0,:])
#pick 2 indexes both rows, third column
print(tensor_three_dim[0:2,:,2])
print(tensor_three_dim[...,:,-1])


tf.Tensor(
[[1 6 7]
 [2 5 7]], shape=(2, 3), dtype=int32)
tf.Tensor([1 6 7], shape=(3,), dtype=int32)
tf.Tensor(
[[7 7]
 [5 3]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[7 7]
 [5 3]
 [8 5]
 [1 2]], shape=(4, 2), dtype=int32)
