In [2]:
import tensorflow as tf

#Absolute value-converts -ve to +ve, +ve to +ve
abs(x)={-x, x<0
        x, x>0}

In [6]:
y_abslt=tf.constant([-2.25,3.25])
tf.abs(y_abslt)
tf.abs(tf.constant(-0.25))

tf.Tensor(0.25, shape=(), dtype=float32)


In [9]:
z_abs_complex=tf.constant([-2.25+4.75j])
tf.abs(z_abs_complex)

<tf.Tensor: shape=(1,), dtype=float64, numpy=array([5.25594901])>

In [10]:
#calculate square root
tf.sqrt([-2.25**2+4.75**2])

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([4.1833], dtype=float32)>

**#Addition,multiplication,divide function**

In [12]:
x1=tf.constant([2,9,9,3,5,6],dtype=tf.int32)
x2=tf.constant([5,7,8,3,5,7],dtype=tf.int32)
print(tf.add(x1,x2))

tf.Tensor([ 7 16 17  6 10 13], shape=(6,), dtype=int32)


#**Broadcasting in tensors**

In [16]:
#broadcasting-smaller tensor is streched out to math the bigger tensor. Here X2 is like [7,7,7,7,7,7]
x1=tf.constant([2,9,9,3,5,6],dtype=tf.int32)
x2=tf.constant([5],dtype=tf.int32)
print(tf.math.add(x1,x2))

tf.Tensor([ 7 14 14  8 10 11], shape=(6,), dtype=int32)


In [22]:
#one row is streched out
x1=tf.constant([[2,9,9,3,5,6],],dtype=tf.int32)
x2=tf.constant([[5],[4],[8]],dtype=tf.int32)
print(x1.shape)
print(x2.shape)
print(tf.math.multiply(x1,x2))

(1, 6)
(3, 1)
tf.Tensor(
[[10 45 45 15 25 30]
 [ 8 36 36 12 20 24]
 [16 72 72 24 40 48]], shape=(3, 6), dtype=int32)


In [13]:
x1=tf.constant([2,9,9,3,5,6],dtype=tf.int32)
x2=tf.constant([5,7,8,3,5,7],dtype=tf.int32)
print(tf.multiply(x1,x2))

tf.Tensor([10 63 72  9 25 42], shape=(6,), dtype=int32)


In [14]:
#If divided by 0, its nan
x1=tf.constant([2,9,9,3,5,6],dtype=tf.int32)
x2=tf.constant([5,7,8,3,0,7],dtype=tf.int32)
print(tf.divide(x1,x2))

tf.Tensor([0.4        1.28571429 1.125      1.                inf 0.85714286], shape=(6,), dtype=float64)


In [15]:
#If divided by 0, no_nan method will handle nan and provide 0 as an o/p
x1=tf.constant([2,9,9,3,5,6],dtype=tf.float32)
x2=tf.constant([5,7,8,3,0,7],dtype=tf.float32)
print(tf.math.divide_no_nan(x1,x2))

tf.Tensor([0.4        1.2857143  1.125      1.         0.         0.85714287], shape=(6,), dtype=float32)


#Maximum within 2 tensors -tf.max
tf.argmax-defines the position of the max value
tf.argmin-defines the minimum value

In [3]:
x1_argmax=tf.constant([[2,9,9,3,5,6],
               [5,7,8,3,0,7],
               [6,5,9,3,1,7]])
print(x1_argmax.shape)
print(tf.math.argmax(x1_argmax))
x2_argmax=tf.constant([[2,9,9,3,5,6],
                       [5,7,8,3,0,7],
                       [6,5,9,3,1,7]])
print(x2_argmax.shape)
# we are fixing the axis to 0, so the comparison will be done based on columns which is y axis
print(tf.math.argmax(x2_argmax,0))

#When changed axis=1, it will compare the rows of each vector
x3_argmax=tf.constant([[2,9,9,3,5,6],
                       [5,7,8,3,0,7],
                       [6,5,9,3,1,7]])
print(x3_argmax.shape)
# we are fixing the axis to 0, so the comparison will be done based on columns which is y axis
print(tf.math.argmax(x3_argmax,axis=1))

(3, 6)
tf.Tensor([2 0 0 0 0 1], shape=(6,), dtype=int64)
(3, 6)
tf.Tensor([2 0 0 0 0 1], shape=(6,), dtype=int64)
(3, 6)
tf.Tensor([1 2 2], shape=(3,), dtype=int64)


In [30]:
x1_argmax=tf.constant([2,9,9,3,5,6])
print(tf.math.argmax(x1_argmax))
x2_argmax=tf.constant([200,9,9,3,5,600])
print(tf.math.argmax(x2_argmax))
x3_argmax=tf.constant([200,9,900,3,5,600])
print(tf.math.argmax(x3_argmax))
x4_argmin=tf.constant([200,9,900,3,5,600])
print(tf.math.argmin(x4_argmin))

tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)


#Other maths function
1.tf.math.equal= Returns the truth value element wise
2.tf.math.power-
3.tf.math.reduce_sum=calculates the sum of all the elements, there are add,divide
4. sigmoid function
5.top_k

In [5]:
x1_pow=tf.constant([2,5,5])
x2_pow=tf.constant([3,4,2])
tf.pow(x1_pow,x2_pow)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([  8, 625,  25], dtype=int32)>

In [12]:
x1_reduce=tf.constant([[2,9,9],
                      [5,7,8],
                      [6,5,9],
                      [4,8,2]],dtype=tf.float16)
#print(x1_reduce)
print(tf.math.reduce_sum(x1_reduce, axis=None, keepdims=False, name=None))
print(tf.math.reduce_max(x1_reduce, axis=None, keepdims=False, name=None))
#When axis=0, calculates the sum of each column
print(tf.math.reduce_sum(x1_reduce, axis=0, keepdims=False, name=None))
#Axis=1, calculates the sum of each row
print(tf.math.reduce_sum(x1_reduce, axis=1, keepdims=False, name=None))
#Finding the mean when axis=0,x axis is fixed, so calculates the column value of each tensor
print(tf.math.reduce_mean(x1_reduce, axis=0, keepdims=False, name=None))

print(tf.math.reduce_mean(x1_reduce, axis=0, keepdims=True, name=None))

tf.Tensor(74.0, shape=(), dtype=float16)
tf.Tensor(9.0, shape=(), dtype=float16)
tf.Tensor([17. 29. 28.], shape=(3,), dtype=float16)
tf.Tensor([20. 20. 20. 14.], shape=(4,), dtype=float16)
tf.Tensor([4.25 7.25 7.  ], shape=(3,), dtype=float16)
tf.Tensor([[4.25 7.25 7.  ]], shape=(1, 3), dtype=float16)


In [14]:
tf.math.top_k(x1_reduce,k=2)

TopKV2(values=<tf.Tensor: shape=(4, 2), dtype=float16, numpy=
array([[9., 9.],
       [8., 7.],
       [9., 6.],
       [8., 4.]], dtype=float16)>, indices=<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[1, 2],
       [2, 1],
       [2, 0],
       [1, 0]], dtype=int32)>)