<a href="https://colab.research.google.com/github/KSingh28/Tensorflow_projects/blob/main/3_TensorflowBsics_LinearAlg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf

#tf.linalg.matmul- total number of columns in the first tensor must match the total number of rows in the second tensor
#neuralearn.ai

In [10]:
x1=tf.constant([[4,3,6],
                [5,1,8]])
x2=tf.constant([[9,2,5],
                [4,3,7],
                [3,2,3]])
tf.linalg.matmul(x1,x2, transpose_a=False, transpose_b=False, adjoint_a=False, adjoint_b=False, a_is_sparse=False,
                  b_is_sparse=False, output_type=None, name=None)


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[66, 29, 59],
       [73, 29, 56]], dtype=int32)>

In [11]:
#Another way to perform matrix multiplication using '@'
print(x1@x2)
x1@x2

tf.Tensor(
[[66 29 59]
 [73 29 56]], shape=(2, 3), dtype=int32)


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[66, 29, 59],
       [73, 29, 56]], dtype=int32)>

#Matrix Transpose- To perform transpose,
#shape value of column x1=shape value of row x2

In [12]:
tf.transpose(x1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[4, 5],
       [3, 1],
       [6, 8]], dtype=int32)>

In [19]:
x1=[[3,5,6],
    [2,7,9]]
x2=[[2,8],
    [4,5],
    [7,7]
    ]
print(tf.transpose(x1).shape,tf.transpose(x2).shape)
print(tf.transpose(x1)@tf.transpose(x2))
#same output when transpose_a=True, transpose_b=True,
tf.linalg.matmul(x1,x2, transpose_a=True, transpose_b=True, adjoint_a=False, adjoint_b=False, a_is_sparse=False,
                  b_is_sparse=False, output_type=None, name=None)

#adjoint value in matmul is same as transpose

(3, 2) (2, 3)
tf.Tensor(
[[ 22  22  35]
 [ 66  55  84]
 [ 84  69 105]], shape=(3, 3), dtype=int32)


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 22,  22,  35],
       [ 66,  55,  84],
       [ 84,  69, 105]], dtype=int32)>